SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;

CREATE TABLE `user` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `avatar_path` varchar(255) DEFAULT NULL,
  `hashed_password` varchar(255) NOT NULL,
  `notifications` int(11) NOT NULL,
  `username` varchar(32) NOT NULL,
  `user_roles_id` bigint(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FKhmd3yu14haupqtsyri0gjpehi` (`user_roles_id`),
  CONSTRAINT `FKhmd3yu14haupqtsyri0gjpehi` FOREIGN KEY (`user_roles_id`) REFERENCES `user_roles` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=455 DEFAULT CHARSET=latin1;

CREATE TABLE `user_roles` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `admin` bit(1) NOT NULL,
  `user` bit(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=455 DEFAULT CHARSET=latin1;

CREATE TABLE `follows` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `followee_id` bigint(20) NOT NULL,
  `follower_id` bigint(20) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `kluch_hashtags` (
  `kluch_id` bigint(20) NOT NULL,
  `hashtags` varchar(255) DEFAULT NULL,
  KEY `FKljcusnc294dscxo4kdt749l53` (`kluch_id`),
  CONSTRAINT `FKljcusnc294dscxo4kdt749l53` FOREIGN KEY (`kluch_id`) REFERENCES `kluchs` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `kluch_mentions` (
  `kluch_id` bigint(20) NOT NULL,
  `mentions` varchar(255) DEFAULT NULL,
  KEY `FK1d81kdd29idhobarfio3ks5aw` (`kluch_id`),
  CONSTRAINT `FK1d81kdd29idhobarfio3ks5aw` FOREIGN KEY (`kluch_id`) REFERENCES `kluchs` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `kluchs` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `author_id` bigint(20) NOT NULL,
  `text` varchar(255) NOT NULL,
  `timestamp` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

CREATE TABLE `persistent_logins` (
  `series` varchar(255) NOT NULL,
  `last_used` datetime NOT NULL,
  `token` varchar(255) NOT NULL,
  `username` varchar(255) NOT NULL,
  PRIMARY KEY (`series`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/**
Hibernate: create table follows (id bigint generated by default as identity, followee_id bigint not null, follower_id bigint not null, primary key (id))
Hibernate: create table kluch_hashtags (kluch_id bigint not null, hashtags varchar(255))
Hibernate: create table kluch_mentions (kluch_id bigint not null, mentions varchar(255))
Hibernate: create table kluchs (id bigint generated by default as identity, author_id bigint not null, text varchar(255) not null, timestamp timestamp not null, primary key (id))
Hibernate: create table persistent_logins (series varchar(255) not null, last_used timestamp not null, token varchar(255) not null, username varchar(255) not null, primary key (series))
Hibernate: create table user (id bigint generated by default as identity, avatar_path varchar(255), hashed_password varchar(255) not null, notifications integer not null check (notifications>=0), username varchar(32) not null, user_roles_id bigint not null, primary key (id))
Hibernate: create table user_roles (id bigint generated by default as identity, admin boolean not null, user boolean not null, primary key (id))
Hibernate: alter table kluch_hashtags add constraint FKljcusnc294dscxo4kdt749l53 foreign key (kluch_id) references kluchs
Hibernate: alter table kluch_mentions add constraint FK1d81kdd29idhobarfio3ks5aw foreign key (kluch_id) references kluchs
Hibernate: alter table user add constraint FKhmd3yu14haupqtsyri0gjpehi foreign key (user_roles_id) references user_roles
*/
